/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecosRouteImport } from './routes/recos'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as ClubRouteImport } from './routes/club'
import { Route as CagnottesRouteImport } from './routes/cagnottes'
import { Route as AnnuaireRouteImport } from './routes/annuaire'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembresIdRouteImport } from './routes/membres.$id'
import { Route as EventsIdRouteImport } from './routes/events_.$id'
import { Route as CagnottesReturnRouteImport } from './routes/cagnottes.return'
import { Route as AuthSetPasswordRouteImport } from './routes/auth.set-password'
import { Route as EventsIdCheckinRouteImport } from './routes/events_.$id_.checkin'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const RecosRoute = RecosRouteImport.update({
  id: '/recos',
  path: '/recos',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const CagnottesRoute = CagnottesRouteImport.update({
  id: '/cagnottes',
  path: '/cagnottes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireRoute = AnnuaireRouteImport.update({
  id: '/annuaire',
  path: '/annuaire',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembresIdRoute = MembresIdRouteImport.update({
  id: '/membres/$id',
  path: '/membres/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events_/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CagnottesReturnRoute = CagnottesReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CagnottesRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdCheckinRoute = EventsIdCheckinRouteImport.update({
  id: '/events_/$id_/checkin',
  path: '/events/$id/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annuaire': typeof AnnuaireRoute
  '/cagnottes': typeof CagnottesRouteWithChildren
  '/club': typeof ClubRoute
  '/evenements': typeof EvenementsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/recos': typeof RecosRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/cagnottes/return': typeof CagnottesReturnRoute
  '/events/$id': typeof EventsIdRoute
  '/membres/$id': typeof MembresIdRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annuaire': typeof AnnuaireRoute
  '/cagnottes': typeof CagnottesRouteWithChildren
  '/club': typeof ClubRoute
  '/evenements': typeof EvenementsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/recos': typeof RecosRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/cagnottes/return': typeof CagnottesReturnRoute
  '/events/$id': typeof EventsIdRoute
  '/membres/$id': typeof MembresIdRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annuaire': typeof AnnuaireRoute
  '/cagnottes': typeof CagnottesRouteWithChildren
  '/club': typeof ClubRoute
  '/evenements': typeof EvenementsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/recos': typeof RecosRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/cagnottes/return': typeof CagnottesReturnRoute
  '/events_/$id': typeof EventsIdRoute
  '/membres/$id': typeof MembresIdRoute
  '/events_/$id_/checkin': typeof EventsIdCheckinRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/annuaire'
    | '/cagnottes'
    | '/club'
    | '/evenements'
    | '/events'
    | '/login'
    | '/messages'
    | '/recos'
    | '/auth/set-password'
    | '/cagnottes/return'
    | '/events/$id'
    | '/membres/$id'
    | '/events/$id/checkin'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/annuaire'
    | '/cagnottes'
    | '/club'
    | '/evenements'
    | '/events'
    | '/login'
    | '/messages'
    | '/recos'
    | '/auth/set-password'
    | '/cagnottes/return'
    | '/events/$id'
    | '/membres/$id'
    | '/events/$id/checkin'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/annuaire'
    | '/cagnottes'
    | '/club'
    | '/evenements'
    | '/events'
    | '/login'
    | '/messages'
    | '/recos'
    | '/auth/set-password'
    | '/cagnottes/return'
    | '/events_/$id'
    | '/membres/$id'
    | '/events_/$id_/checkin'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnuaireRoute: typeof AnnuaireRoute
  CagnottesRoute: typeof CagnottesRouteWithChildren
  ClubRoute: typeof ClubRoute
  EvenementsRoute: typeof EvenementsRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  RecosRoute: typeof RecosRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  EventsIdRoute: typeof EventsIdRoute
  MembresIdRoute: typeof MembresIdRoute
  EventsIdCheckinRoute: typeof EventsIdCheckinRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recos': {
      id: '/recos'
      path: '/recos'
      fullPath: '/recos'
      preLoaderRoute: typeof RecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cagnottes': {
      id: '/cagnottes'
      path: '/cagnottes'
      fullPath: '/cagnottes'
      preLoaderRoute: typeof CagnottesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire': {
      id: '/annuaire'
      path: '/annuaire'
      fullPath: '/annuaire'
      preLoaderRoute: typeof AnnuaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membres/$id': {
      id: '/membres/$id'
      path: '/membres/$id'
      fullPath: '/membres/$id'
      preLoaderRoute: typeof MembresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$id': {
      id: '/events_/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cagnottes/return': {
      id: '/cagnottes/return'
      path: '/return'
      fullPath: '/cagnottes/return'
      preLoaderRoute: typeof CagnottesReturnRouteImport
      parentRoute: typeof CagnottesRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$id_/checkin': {
      id: '/events_/$id_/checkin'
      path: '/events/$id/checkin'
      fullPath: '/events/$id/checkin'
      preLoaderRoute: typeof EventsIdCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CagnottesRouteChildren {
  CagnottesReturnRoute: typeof CagnottesReturnRoute
}

const CagnottesRouteChildren: CagnottesRouteChildren = {
  CagnottesReturnRoute: CagnottesReturnRoute,
}

const CagnottesRouteWithChildren = CagnottesRoute._addFileChildren(
  CagnottesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnuaireRoute: AnnuaireRoute,
  CagnottesRoute: CagnottesRouteWithChildren,
  ClubRoute: ClubRoute,
  EvenementsRoute: EvenementsRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  RecosRoute: RecosRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  EventsIdRoute: EventsIdRoute,
  MembresIdRoute: MembresIdRoute,
  EventsIdCheckinRoute: EventsIdCheckinRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
